### ISSUE TITLE
Create the Menu

### ISSUE THREAD

**Issue by ReznorW** [ReznorW/Library-App#1]
3 Options:
-Barcode Scanner
-Manual Lookup
-Map

**Comment by sir-vancelot** [comment]
![image](https://user-images.githubusercontent.com/22999101/101539675-e4a1eb00-396c-11eb-9c8e-373684b0a565.png)

**Comment by sir-vancelot** [comment]
![image](https://user-images.githubusercontent.com/22999101/101552620-23da3700-3981-11eb-9e42-d2b14b2932ec.png)
